const BIBLE_BOOKS = [
    { id: "1-01", name: "창세기", short: "창", test: "old", chapters: 50 },
    { id: "1-02", name: "출애굽기", short: "출", test: "old", chapters: 40 },
    { id: "1-03", name: "레위기", short: "레", test: "old", chapters: 27 },
    { id: "1-04", name: "민수기", short: "민", test: "old", chapters: 36 },
    { id: "1-05", name: "신명기", short: "신", test: "old", chapters: 34 },
    { id: "1-06", name: "여호수아", short: "수", test: "old", chapters: 24 },
    { id: "1-07", name: "사사기", short: "삿", test: "old", chapters: 21 },
    { id: "1-08", name: "룻기", short: "룻", test: "old", chapters: 4 },
    { id: "1-09", name: "사무엘상", short: "삼상", test: "old", chapters: 31 },
    { id: "1-10", name: "사무엘하", short: "삼하", test: "old", chapters: 24 },
    { id: "1-11", name: "열왕기상", short: "왕상", test: "old", chapters: 22 },
    { id: "1-12", name: "열왕기하", short: "왕하", test: "old", chapters: 25 },
    { id: "1-13", name: "역대상", short: "대상", test: "old", chapters: 29 },
    { id: "1-14", name: "역대하", short: "대하", test: "old", chapters: 36 },
    { id: "1-15", name: "에스라", short: "스", test: "old", chapters: 10 },
    { id: "1-16", name: "느헤미야", short: "느", test: "old", chapters: 13 },
    { id: "1-17", name: "에스더", short: "에", test: "old", chapters: 10 },
    { id: "1-18", name: "욥기", short: "욥", test: "old", chapters: 42 },
    { id: "1-19", name: "시편", short: "시", test: "old", chapters: 150 },
    { id: "1-20", name: "잠언", short: "잠", test: "old", chapters: 31 },
    { id: "1-21", name: "전도서", short: "전", test: "old", chapters: 12 },
    { id: "1-22", name: "아가", short: "아", test: "old", chapters: 8 },
    { id: "1-23", name: "이사야", short: "사", test: "old", chapters: 66 },
    { id: "1-24", name: "예레미야", short: "렘", test: "old", chapters: 52 },
    { id: "1-25", name: "예레미야 애가", short: "애", test: "old", chapters: 5 },
    { id: "1-26", name: "에스겔", short: "겔", test: "old", chapters: 48 },
    { id: "1-27", name: "다니엘", short: "단", test: "old", chapters: 12 },
    { id: "1-28", name: "호세아", short: "호", test: "old", chapters: 14 },
    { id: "1-29", name: "요엘", short: "욜", test: "old", chapters: 3 },
    { id: "1-30", name: "아모스", short: "암", test: "old", chapters: 9 },
    { id: "1-31", name: "오바디야", short: "옵", test: "old", chapters: 1 },
    { id: "1-32", name: "요나", short: "욘", test: "old", chapters: 4 },
    { id: "1-33", name: "미가", short: "미", test: "old", chapters: 7 },
    { id: "1-34", name: "나훔", short: "나", test: "old", chapters: 3 },
    { id: "1-35", name: "하박국", short: "합", test: "old", chapters: 3 },
    { id: "1-36", name: "스바냐", short: "습", test: "old", chapters: 3 },
    { id: "1-37", name: "학개", short: "학", test: "old", chapters: 2 },
    { id: "1-38", name: "스가랴", short: "슥", test: "old", chapters: 14 },
    { id: "1-39", name: "말라기", short: "말", test: "old", chapters: 4 },
    { id: "2-01", name: "마태복음", short: "마", test: "new", chapters: 28 },
    { id: "2-02", name: "마가복음", short: "막", test: "new", chapters: 16 },
    { id: "2-03", name: "누가복음", short: "눅", test: "new", chapters: 24 },
    { id: "2-04", name: "요한복음", short: "요", test: "new", chapters: 21 },
    { id: "2-05", name: "사도행전", short: "행", test: "new", chapters: 28 },
    { id: "2-06", name: "로마서", short: "롬", test: "new", chapters: 16 },
    { id: "2-07", name: "고린도전서", short: "고전", test: "new", chapters: 16 },
    { id: "2-08", name: "고린도후서", short: "고후", test: "new", chapters: 13 },
    { id: "2-09", name: "갈라디아서", short: "갈", test: "new", chapters: 6 },
    { id: "2-10", name: "에베소서", short: "엡", test: "new", chapters: 6 },
    { id: "2-11", name: "빌립보서", short: "빌", test: "new", chapters: 4 },
    { id: "2-12", name: "골로새서", short: "골", test: "new", chapters: 4 },
    { id: "2-13", name: "데살로니가전서", short: "살전", test: "new", chapters: 5 },
    { id: "2-14", name: "데살로니가후서", short: "살후", test: "new", chapters: 3 },
    { id: "2-15", name: "디모데전서", short: "딤전", test: "new", chapters: 6 },
    { id: "2-16", name: "디모데후서", short: "딤후", test: "new", chapters: 4 },
    { id: "2-17", name: "디도서", short: "딛", test: "new", chapters: 3 },
    { id: "2-18", name: "빌레몬서", short: "몬", test: "new", chapters: 1 },
    { id: "2-19", name: "히브리서", short: "히", test: "new", chapters: 13 },
    { id: "2-20", name: "야고보서", short: "약", test: "new", chapters: 5 },
    { id: "2-21", name: "베드로전서", short: "벧전", test: "new", chapters: 5 },
    { id: "2-22", name: "베드로후서", short: "벧후", test: "new", chapters: 3 },
    { id: "2-23", name: "요한1서", short: "요일", test: "new", chapters: 5 },
    { id: "2-24", name: "요한2서", short: "요이", test: "new", chapters: 1 },
    { id: "2-25", name: "요한3서", short: "요삼", test: "new", chapters: 1 },
    { id: "2-26", name: "유다서", short: "유", test: "new", chapters: 1 },
    { id: "2-27", name: "요한계시록", short: "계", test: "new", chapters: 22 }
];

const SAMPLE_DATA = {
    "1-01": {
        1: [
            "창1:1 <천지 창조> 태초에 하나님이 천지를 창조하시니라",
            "창1:2 땅이 혼돈하고 공허하며 흑암이 깊음 위에 있고 하나님의 영은 수면 위에 운행하시니라",
            "창1:3 하나님이 이르시되 빛이 있으라 하시니 빛이 있었고",
            "창1:4 빛이 하나님이 보시기에 좋았더라 하나님이 빛과 어둠을 나누사",
            "창1:5 하나님이 빛을 낮이라 부르시고 어둠을 밤이라 부르시니라 저녁이 되고 아침이 되니 이는 첫째 날이니라"
        ]
    }
};

export { BIBLE_BOOKS, SAMPLE_DATA };
